### ISSUE TITLE
Firebase cost and comparison

### ISSUE THREAD

**Issue by ktsuench** [ruhacks/tasks#3]
Give a cost and comparison summary on Firebase.
- What does it provide?
- For the services/products it provides that we may use, is the cost reasonable?
  - or what are the available plans and specs we can choose from? (_provide link or list_)
- Is it easy to implement those services/products? (_a.k.a. ease of use_)
- In comparison to MongoDB:
  - is it easier to set up?
  - is it easier to use?
  - does it provide more services/products to lessen our work?

__Comment summary in this issue.__

**Comment by zsalehi** [comment]
Google Firebase seems like a great alternative then building in Heroku or Digital Ocean. Yes the customizability may be a little limited and our data is in Google's hands but I believe that it may be worth the look considering the fact that auth, database support, dynamic server response for chatbot style form is all capable and very well documented on Google Firebase. Plus I believe that it is pretty cost effective for us. I talked to another dev that I am close with and he said the free tier should also be plenty for us to get started and work on for the typical load that we will receive.

**Comment by smehtaca** [comment]
Firebase is a suite of products provided by Google which includes Authentication, Cloud Storage, Cloud Functions databases, and more.

Firebase Pros:

-Cheap( I believe the free plan could be good enough for our purposes, pricing here: https://firebase.google.com/pricing/)
-No need to manage or setup servers as cloud hosting is free and handled via Google CDNs and hosting 
-Easy to authenticate users(OAuth, Google log-in etc.)
-Built-in scaleable noSQL databases
-Cloud storage built in so we can store hacker pictures and resumes.
-Cloud Functions can be used to build a serverless and scaleable backend so that we can have our own custom code and not be as heavily dependent on Google's services i.e. we could have our own authentication system we if so wanted.
-Easy to setup analytics to track visitors.
-Cloud Messaging(We could use this to allow hackers to message volunteers or setup our own Slack clone)

Cons

-Might be overkill for our uses
-May end up being overly dependent on Google Services( Facebook used to have a similar service called Parse which it shut down; I don't think it's likely that Google will do this but who knows)
-Privacy issues as servers are not under our control and private data may be hosted in the US.

**Comment by smehtaca** [comment]
Additional comparisions:

Firebase vs. DO
https://stackshare.io/stackups/firebase-vs-heroku

Firebase vs. Heroku
https://stackshare.io/stackups/firebase-vs-heroku

**Comment by smehtaca** [comment]
Another comparision against EC2

https://stackshare.io/stackups/amazon-ec2-vs-firebase-vs-heroku

**Comment by ktsuench** [comment]
## Summary of Services:
[Firebase](https://firebase.google.com) is a ___realtime database and api___.
[Heroku](https://heroku.com) is a ___Platform as a Service___ a.k.a. ___PaaS___.
[DigitalOcean](https://digitalocean.com) is a ___cloud hosting platform___.

## Conclusion
It's actually difficult to compare the three as they provide different solutions with varying levels of flexibility. The best we can do is stick with one and build our solution around it.

## Proposed Plan
_Will add by end of today_

**Comment by ktsuench** [comment]
## Proposed Solution

We can try using Firebase database along with its authentication and admin SDK to integrate it into our application which will be hosted on DigitalOcean. The reasoning for this is because we still want to host the old website and hosting on DigitalOcean will give us the flexibility to change up the stack if required. As well in terms of long term thinking, we can move forward with the same host in future years while allowing stack options to vary.

___What do you guys thinks?___
